### PR TITLE
Add sound generation api

### PR DESCRIPTION
**Pull request by supagroova**
Adds support for the new [Sound Generation](https://elevenlabs.io/docs/api-reference/sound-generation) API.

### CODE REVIEW

**Comment by supagroova** [comment]
LGTM

**Comment by taigrr** [comment]
I'm down to merge this, but can you fix up the package URL name? i.e. s/supagroova/taigrr/g

**Comment by supagroova** [comment]
Apologies for that oversight. Done ✅

**Comment by taigrr** [comment]
awesome! thanks for the contribution!

**Pull request merged**
